// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBisFIUbg72hyX8IzAO_YR-QGHAs14hfTY',
    appId: '1:744452582274:web:fe78827d64353250f1fd9b',
    messagingSenderId: '744452582274',
    projectId: 'studio-6266778512-644c0',
    authDomain: 'studio-6266778512-644c0.firebaseapp.com',
    storageBucket: 'studio-6266778512-644c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXLcOnhbQ8pQ5bba6hGgbWMihfxp87aOM',
    appId: '1:46784462538:android:f2a33ffaf8f7b6be1dbe33',
    messagingSenderId: '46784462538',
    projectId: 'book-app-65107445-681db',
    storageBucket: 'book-app-65107445-681db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PDfjS-WmhAReLRR2eEFz61NkRIEL03k',
    appId: '1:46784462538:ios:acabe6bb11c8e32f1dbe33',
    messagingSenderId: '46784462538',
    projectId: 'book-app-65107445-681db',
    storageBucket: 'book-app-65107445-681db.firebasestorage.app',
    iosClientId: '46784462538-8hcvu1e01bjvvscn9oeg2v7apop6k94f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

}